### ISSUE TITLE
Function calls with no arguments throw TypeError

### ISSUE THREAD

**Issue by vpzomtrrfrt** [dogescript/dogescript#176]
```
DOGE> very a is plz b with
/home/colin/dogescript/lib/parser.js:552
  var chained = tokens[tokens.length - 1].slice(-1) === '&';
                                          ^

TypeError: Cannot read property 'slice' of undefined
    at handleWith (/home/colin/dogescript/lib/parser.js:552:43)
    at functionInvocation (/home/colin/dogescript/lib/parser.js:744:25)
    at handlePlz (/home/colin/dogescript/lib/parser.js:776:16)
    at parse (/home/colin/dogescript/lib/parser.js:925:14)
    at parse (/home/colin/dogescript/lib/parser.js:962:24)
    at Stream._transform (/home/colin/dogescript/bin/dogescript.js:68:22)
    at Stream.Transform._read (_stream_transform.js:190:10)
    at Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:415:12)
    at writeOrBuffer (_stream_writable.js:399:5)
```

**Comment by AnEmortalKid** [comment]
Hmm that error should be better and tell you that it expected arguments.

Iirc for no arguments you would do

very a is plz b

**Comment by AnEmortalKid** [comment]
If you have `with` , we expect arguments. So we should report that not having args after with is not valid. H
The appropriate call would be `foo dose bar` to produce `foo.bar()`
