### ISSUE TITLE
dogescript binary behaving incorrectly

### ISSUE THREAD

**Issue by AnEmortalKid** [dogescript/dogescript#252]
The `dogescript` binary used to work when installed globally.

## Current state

```
JMonterrubio@RaccoonGames MINGW64 /j/Workspaces/dogescript (master)
$ npm i . -g
C:\Users\JMonterrubio\AppData\Roaming\npm\dogescript -> C:\Users\JMonterrubio\AppData\Roaming\npm\node_modules\dogescript\bin\dogescript.bin.js
+ dogescript@2.4.0-pre
updated 1 package in 3.317s

JMonterrubio@RaccoonGames MINGW64 /j/Workspaces/dogescript (master)
$ dogescript
C:\Users\JMonterrubio\AppData\Roaming\npm/node_modules/dogescript/bin/dogescript.bin.js: line 1: import: command not found
C:\Users\JMonterrubio\AppData\Roaming\npm/node_modules/dogescript/bin/dogescript.bin.js: line 2: import: command not found
C:\Users\JMonterrubio\AppData\Roaming\npm/node_modules/dogescript/bin/dogescript.bin.js: line 3: import: command not found
C:\Users\JMonterrubio\AppData\Roaming\npm/node_modules/dogescript/bin/dogescript.bin.js: line 4: import: command not found
C:\Users\JMonterrubio\AppData\Roaming\npm/node_modules/dogescript/bin/dogescript.bin.js: line 5: import: command not found
C:\Users\JMonterrubio\AppData\Roaming\npm/node_modules/dogescript/bin/dogescript.bin.js: line 6: import: command not found
C:\Users\JMonterrubio\AppData\Roaming\npm/node_modules/dogescript/bin/dogescript.bin.js: line 7: import: command not found
C:\Users\JMonterrubio\AppData\Roaming\npm/node_modules/dogescript/bin/dogescript.bin.js: line 8: import: command not found
C:\Users\JMonterrubio\AppData\Roaming\npm/node_modules/dogescript/bin/dogescript.bin.js: line 9: import: command not found
C:\Users\JMonterrubio\AppData\Roaming\npm/node_modules/dogescript/bin/dogescript.bin.js: line 10: import: command not found
C:\Users\JMonterrubio\AppData\Roaming\npm/node_modules/dogescript/bin/dogescript.bin.js: line 12: syntax error near unexpected token `('
C:\Users\JMonterrubio\AppData\Roaming\npm/node_modules/dogescript/bin/dogescript.bin.js: line 12: `var argv = optimist.usage('Usage: dogescript <file> [options]').argv;'

```

## running from dist

```
JMonterrubio@RaccoonGames MINGW64 /j/Workspaces/dogescript (master)
$ ./dist/dogescript.bin.js
[dogescript@2.4.0-pre]
```

## running from .bin

```
JMonterrubio@RaccoonGames MINGW64 /j/Workspaces/dogescript (master)
$ ./bin/dogescript.bin.js
./bin/dogescript.bin.js: line 1: import: command not found
./bin/dogescript.bin.js: line 2: import: command not found
./bin/dogescript.bin.js: line 3: import: command not found
./bin/dogescript.bin.js: line 4: import: command not found
./bin/dogescript.bin.js: line 5: import: command not found
./bin/dogescript.bin.js: line 6: import: command not found
./bin/dogescript.bin.js: line 7: import: command not found
./bin/dogescript.bin.js: line 8: import: command not found
./bin/dogescript.bin.js: line 9: import: command not found
./bin/dogescript.bin.js: line 10: import: command not found
./bin/dogescript.bin.js: line 12: syntax error near unexpected token `('
./bin/dogescript.bin.js: line 12: `var argv = optimist.usage('Usage: dogescript <file> [options]').argv;'

JMonterrubio@RaccoonGames MINGW64 /j/Workspaces/dogescript (master)
$ node ./bin/dogescript.bin.js
J:\Workspaces\dogescript\bin\dogescript.bin.js:1
import fs from 'fs';
^^^^^^

SyntaxError: Cannot use import statement outside a module
?[90m    at Module._compile (internal/modules/cjs/loader.js:891:18)?[39m
?[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10
)?[39m
?[90m    at Module.load (internal/modules/cjs/loader.js:811:32)?[39m
?[90m    at Function.Module._load (internal/modules/cjs/loader.js:723:14)?[39m
?[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)?[39
m
?[90m    at internal/main/run_main_module.js:17:11?[39m
```

My guess is somehow what we wanted in the `./dist` isn't making it over to `.bin`

**Comment by Pholey** [comment]
Ah i think i see what's happening here. If we look at the package.json, `bin` was erroneously set to:
```
  "bin": "./bin/dogescript.bin.js",
```

it should be something like:
```
  "bin": "./dist/dogescript.bin.js",
```

when you see errors like this:
```
./bin/dogescript.bin.js: line 2: import: command not found
```
This generally means that newer JS syntax was used in an environment where it wasn't supported (basically, an older version of js that doesn't have `import foo from "bar"`). In other words one can deduce that something didn't get transpiled correctly from here

if we look at the webpack config to find out how that file is getting transpiled we see something interesting:
```
  entry: {
    "dogescript": "./index.js",
    "dogescript.bin": "./bin/dogescript.bin.js"
  },
```
`./bin/dogescript.bin.js` is actually configured one of the starting points of compilation in webpack, in other words it is not at all the transpiled binary, but what webpack actually reads from for compilation. 

I included a PR here: https://github.com/dogescript/dogescript/pull/253

**Comment by AnEmortalKid** [comment]
Ah that make sense, and explains why `.bin` was funky but the `.dist` one worked the way we wanted it.
